package model;
// Generated 17-ene-2020 18:53:35 by Hibernate Tools 4.3.1.Final

/**
 * Biblioteca generated by hbm2java
 */
public class Biblioteca implements java.io.Serializable {

	private Integer idBiblioteca;
	private String nombreBiblioteca;

	public Biblioteca() {
	}

	public Biblioteca(String nombreBiblioteca) {
		this.nombreBiblioteca = nombreBiblioteca;
	}

	public Integer getIdBiblioteca() {
		return this.idBiblioteca;
	}

	public void setIdBiblioteca(Integer idBiblioteca) {
		this.idBiblioteca = idBiblioteca;
	}

	public String getNombreBiblioteca() {
		return this.nombreBiblioteca;
	}

	public void setNombreBiblioteca(String nombreBiblioteca) {
		this.nombreBiblioteca = nombreBiblioteca;
	}

}
