package model;
// Generated 17-ene-2020 18:53:35 by Hibernate Tools 4.3.1.Final

/**
 * Llibres generated by hbm2java
 */
public class Llibres implements java.io.Serializable {

	private Integer idLlibre;
	private Autor autor;
	private String nomLlibre;
	private String editorial;

	public Llibres() {
	}

	public Llibres(Autor autor, String nomLlibre, String editorial) {
		this.autor = autor;
		this.nomLlibre = nomLlibre;
		this.editorial = editorial;
	}

	public Integer getIdLlibre() {
		return this.idLlibre;
	}

	public void setIdLlibre(Integer idLlibre) {
		this.idLlibre = idLlibre;
	}

	public Autor getAutor() {
		return this.autor;
	}

	public void setAutor(Autor autor) {
		this.autor = autor;
	}

	public String getNomLlibre() {
		return this.nomLlibre;
	}

	public void setNomLlibre(String nomLlibre) {
		this.nomLlibre = nomLlibre;
	}

	public String getEditorial() {
		return this.editorial;
	}

	public void setEditorial(String editorial) {
		this.editorial = editorial;
	}

}
