package model;
// Generated 17-ene-2020 18:53:35 by Hibernate Tools 4.3.1.Final

/**
 * Persona generated by hbm2java
 */
public class Persona implements java.io.Serializable {

	private int dni;
	private String nombrePersona;
	private int telefon;

	public Persona() {
	}

	public Persona(int dni, String nombrePersona, int telefon) {
		this.dni = dni;
		this.nombrePersona = nombrePersona;
		this.telefon = telefon;
	}

	public int getDni() {
		return this.dni;
	}

	public void setDni(int dni) {
		this.dni = dni;
	}

	public String getNombrePersona() {
		return this.nombrePersona;
	}

	public void setNombrePersona(String nombrePersona) {
		this.nombrePersona = nombrePersona;
	}

	public int getTelefon() {
		return this.telefon;
	}

	public void setTelefon(int telefon) {
		this.telefon = telefon;
	}

}
